### ISSUE TITLE
It must have server id to report now?

### ISSUE THREAD

**Issue by crx9** [codsec/CSGO-ReportBot#5]

**Comment by crx9** [comment]
Can't bot just report cheaters after a game like before?

**Comment by crx9** [comment]
_   ___         _                        _      _       _
  | |_|_  |  ___ _| |   ___ ___ ___ ___ ___| |_   | |_ ___| |_
  | . |_| |_|  _| . |  |  _| -_| . | . |  _|  _|  | . | . |  _|
  |___|_____|_| |___|  |_| |___|  _|___|_| |_|    |___|___|_|
                               |_|
  ᴠᴇʀsɪᴏɴ 2.4.0    @ᴄᴏᴅsᴇᴄ    ʟᴀᴛᴇsᴛ ᴜᴘᴅᴀᴛᴇ: 12/07/2019

 [!] Loading...
{ Error: connect ECONNREFUSED 151.101.0.133:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '151.101.0.133',
  port: 443 } Promise {
  <rejected> { Error: connect ECONNREFUSED 151.101.0.133:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '151.101.0.133',
    port: 443 } }

**Comment by codsec** [comment]
> Can't bot just report cheaters after a game like before?

no, this is no longer possible after valve updates, now for reportbot to work correctly you need to report during the match and specify serverid
