### ISSUE TITLE
askSteamGuard

### ISSUE THREAD

**Issue by rabell69** [codsec/CSGO-ReportBot#7]
TypeError: Cannot read property 'askSteamGuard' of undefined
    at C:\Users\rabell69\Downloads\CSGO-ReportBot-b1rd-master\CSGO-ReportBot-b1rd-master\report.js:188:45 Promise {
  <rejected> TypeError: Cannot read property 'askSteamGuard' of undefined
      at C:\Users\rabell69\Downloads\CSGO-ReportBot-b1rd-master\CSGO-ReportBot-b1rd-master\report.js:188:45
}

**Comment by codsec** [comment]
Are you using steam guard enabled accounts?

**Comment by rabell69** [comment]
all accounts have disable guard

**Comment by codsec** [comment]
> all accounts have disable guard

Send me a print of your config file (make sure you don't show your steam api key)

**Comment by rabell69** [comment]
https://prnt.sc/q8g3wp

**Comment by codsec** [comment]
> https://prnt.sc/q8g3wp

First of all, let your
"match ID": "0", and don't use "auto"

I will investigate the problem...wait
